### PR TITLE
Toggle check for latest version at startup

### PR DESCRIPTION
**Pull request by mathieucarbou**
This is a first PR that enabled me to dive a little into the project.

I wanted at a time to stick with an older version, but the popup at startup was annoying me. So this adds a toggle to deactivate version check at startup.

### CODE REVIEW

**Comment by mathieucarbou** [comment]
rebased on develop just now.

**Comment by rsjaffe** [comment]
Application already has code that limits update announcement to once per version. Was that not working?

**Comment by mathieucarbou** [comment]
Actually it was not working: when I tried a previous version and wanted to stick to it, each time I opened Lightroom, a popup appeared saying a new version is available. What I wanted is having the ability to disable this version check.

**Comment by mathieucarbou** [comment]
I checked again and actually sorry it was my mistake. I think I manually edited or removed the MIDI2LR.xml file. I read the code again and it does the right think :-)

But... The downside of having this check done only once is that if the user missed it by mistake, he is not informed anymore. Perhaps a better way would be to check __each time__ for a new version and show to the user a message, except if he explicitly disables the check.

So I'll much more update the PR to leave this checkbox and do the check each time and display a popup each time.

**Comment by mathieucarbou** [comment]
updated Pr and rebased

**Comment by mathieucarbou** [comment]
Actually, when. I wanted to rollback and stick to a previous version of the
plugin, the pop-up displayed at each startup so this was quite annoying.
This is to disallow the check completely then.

-- Mathieu

**Comment by rsjaffe** [comment]
I'm still not sure that this is better behavior. I'm going to play around with this after November and see what will work best for people. The current behavior is the result of user feedback.

**Comment by mathieucarbou** [comment]
Looking at what other software usually do, they offer an option to check for updates, and it can be deactivated, or re-activated, the idea being that you cannot miss an update, which you can now if you close the popup by mistake.

**Comment by mathieucarbou** [comment]
rebased

**Comment by mathieucarbou** [comment]
rebased

**Comment by mathieucarbou** [comment]
rebased on 1.5.0.0 - develop

**Pull request closed without merging**
