### PR TITLE
Local Adjustment Presets

### PR DESCRIPTION
**Pull request by CSaulnier**
Overwrote ActionSeries 5-9 functions to Apply Local Preset.

Specify your Local Adjustment Presets (eg: 'Burn (Darken).lrtemplate' : without quotes) in LR - Plug-in Extras - midi2lr Options - Series of commands.

image

### CODE REVIEW

**Comment by CSaulnier** [comment]
lol... Ignore #5 in my screen preview as that was a test! :)

**Comment by rsjaffe** [comment]
Nice work! I'll add a new dialog tab for that. I'm also going to work on integrating that into the menu layout.  That starts with editing Database.lua, regenerating the other files via a MIDI2LR app option in Lightroom, then moving the new C++ files into the application source directory. It's a bit of a complicated mess, but that's the way I use a database to generate much of the code and documentation.

**Comment by rsjaffe** [comment]
Now all that's left is making the menu.

**Comment by CSaulnier** [comment]
Excellent.... thanks Rory.  That does sound like a complicated mess. :)   I envision the midi2lr application listing the actual presets when assigning them to a note instead of mapping them in options.   The preset name would then be passed along to applylocalpreset() from midi2lr as an additional paramenter to the local preset action.  I don't know how difficult this would be, but it would be a rather simple interface for the end user.

**Comment by CSaulnier** [comment]
Something like this... with or without the file extension.    The sent ACTION from midi2lr could be something like 'LocalPreset:Iris Enhance.lrtemplate".    The parameter for the ACTION would be delimited with the filename.  The ACTION:FILENAME could be split.  The FILENAME would be sent to ApplyLocalPreset().   This would allow the end user to have an unlimited set of presets applied.   The same logic could be done for Develop Presets.   Instead of having ACTIONs Preset_1 to Preset_40 you could have one function.  Does this make sense?
image

**Comment by rsjaffe** [comment]
The problem is with revising the menus based on information in the plugin. The two pieces don't always communicate. The bigger problem, and one that I intend to eventually address, is that the menu structure in the app is static.

**Comment by CSaulnier** [comment]
I haven't looked at the app code so just throwing this out there... what if the plugin first gathered a list of develop and local presets when it loads and saves them out to a preference file.   Afterwards when the app is loaded it could read the presets from the pref file and display them in the app menus.   This way both the plug-in and app would be in sync as at the time it's started.   Just an idea.

**Comment by rsjaffe** [comment]
Merged into master

**Pull request closed without merging**
