### PR TITLE
Popup List for selecting Local Presets

### PR DESCRIPTION
**Pull request by CSaulnier**
Cleaner interface for selecting Local Presets.  No need to check for file extensions.
Also added the 3 ApplyLocalPreset functions (6-8) to client.lua

### CODE REVIEW

**Comment by CSaulnier** [comment]
Here's an example for my settings.
image

**Comment by rsjaffe** [comment]
Looks great! I'm going to do one minor change to make this friendlier to foreign language users. Then I'll merge it in. It should be ready in time for the official 2.5 release.

**Comment by rsjaffe** [comment]
merged into develop

**Comment by CSaulnier** [comment]
Beauty! :)  Thanks Rory!

**Pull request merged**
