### PR TITLE
fixed compil issue and generated files

### PR DESCRIPTION
**Pull request by mathieucarbou**

### CODE REVIEW

**Comment by mathieucarbou** [comment]
every occurences ? there's penty of `short controlnumber` in the .h file

**Comment by rsjaffe** [comment]
No, just for ChannelModel::controllerToPlugin. So you'd revert the change in the ControlsModel.h file and change the type in the ControlsModel.cpp file. I don't know how to edit pull requests or I'd do it myself. If you could make the change I'd appreciate it.

What happened is that I changed the type for controlnumber in ChannelModel to size_t

**Comment by rsjaffe** [comment]
It remains _short_ in ControlsModel.

**Comment by mathieucarbou** [comment]
ok :-)

**Pull request merged**
