### PR TITLE
HSL B&W: Moving all saturation sliders at once

### PR DESCRIPTION
**Pull request by mathieucarbou**
This PR is to allow some faders to control several Lightroom sliders at once.

This can be useful for example to control from one slider the amount of saturation for all colors.

I have on my TouchOSC app this slider (the one below): HSL B&W:

And when it moves, it automatically updates all saturation slides at once:

There is also a reset button to reset all saturation sliders at once, and the HSL B&W slider moves as the red saturation moves (meaning if you move the red saturation slider, it will also move this one)

This is a specific example but the more general use case would be to have a fader that can control several other sliders. This could also be called as an "opacity" slider, that would apply some settings gradually.

In MIDI2L I added 2 menu items so that we can bind them:
- Saturation Adjustements: for the fader
- Reset Saturation Adjustements: for the button

### CODE REVIEW

**Comment by mathieucarbou** [comment]
updated Pr and rebased

**Comment by mathieucarbou** [comment]
Perhaps is can be also related to https://groups.google.com/forum/#!topic/midi2lr/KB4sZUA3o74 ?

The idea behind this would be to be able to map a slider, or a button, to several commands. If they are buttons, then commands are executed sequentially, and if they are sliders, all the values are moved the same.

Having the ability to do some multi-mappings would also resolve this feature I think, directly by mapping several HSL values for 1 midi command.

**Comment by mathieucarbou** [comment]
rebased

**Comment by mathieucarbou** [comment]
rebased

**Comment by mathieucarbou** [comment]
rebased on 1.5.0.0 - develop

**Comment by mathieucarbou** [comment]
@rsjaffe : pr rebased on 1336ff7c07701f0e316a92772759009bb7ac9fe8

**Comment by rsjaffe** [comment]
This needs to be rewritten so that there are no changes to MIDI2LR.CLIENT--adding things there unnecessarily slows down a critical loop. Lua handles associative tables very efficiently as hash tables, and that's where the added functions need to go.

If the action doesn't need the message value then it should be added to the ACTIONS table.

if the action does need the message value then it should be added to the SETTINGS table.

Also, the change to AdjustmentChangeObserver is inside a loop--it will be evaluated unnecessarily often. I would prefer to see this removed from the AdjustmentChangeObserver if possible. If not, it needs to be placed where it'll have minimal effect on speed.

Any new tables (e.g., MULTI_MIDI_TO_LR) need to go into ClientUtilities, not Client.

**Comment by mathieucarbou** [comment]
ok! will work on it as soon as I can :-) Thanks for the review!

**Pull request merged**
