### PR TITLE
Fix problems with knobs values restore

### PR DESCRIPTION
**Pull request by AndyMcFishka**
-get rid of duplicated refresh midi controller code
-fix problem with knob values restore at profile switch
-higher priority to alt param value
-nil checks fixed

### CODE REVIEW

**Comment by AndyMcFishka** [comment]
related to https://github.com/rsjaffe/MIDI2LR/discussions/756 and https://github.com/rsjaffe/MIDI2LR/discussions/762#discussioncomment-7808510

**Comment by AndyMcFishka** [comment]
Exposure problems are fixed, but it seems that Contrast knob problems are still here...

**Comment by Darek24Szubi** [comment]
Super information!

Please let me know the safest way to make these changes? 
Is there any way to swap files simply and it will be ok?

OK - I've swapped files and everything looks promising so far - thanks!

**Comment by AndyMcFishka** [comment]
> Super information!
> 
> Please let me know the safest way to make these changes? Is there any way to swap files simply and it will be ok?
> 
> OK - I've swapped files and everything looks promising so far - thanks!

Glad to hear that it fixed the problem for you. For everybody with the same question - yes, you can replace files and restart plugin, thats all

**Review by rsjaffe — APPROVED** [review]
Thank you for your fixes. Will merge and then refactor as local work not yet pushed to github has refactored FullRefresh to reduce dependencies and get rid of duplicate function.

**Pull request merged**
